name: Execute Overall Project Testing & Dependency Scanning
on:
  push:
    branches: ["*"]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["main", "release/*"]
env:
  HUSKY: 0
jobs:
  execute_test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Node Runtime
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Test
        run: npm run test
